resmgr/zenpacks.json
zenpack_versions.json

Short of overlooking a ZP, this PR should finish off the initial set of zenpacks for Metis Core and RM.  There are 4 separate commits that detail the different operations - basically, filling in missing gaps and normalizing some discrepancies.

Update zenpack info

---

Jenkins-image.groovy
artifact_download.py
core/Dockerfile.in
core/makefile
product-base/install_scripts/zenoss_component_install.sh
resmgr/Dockerfile.in
resmgr/makefile

Gives QA a breadcrumb trail about which builds/git-refs went into a particular build for nightlies.

Add download logs to the product images

---

artifact_download.py
zenpack_versions.json

Updated zenpack_versions.json to use the new "zenpack" downloader type
for all ZenPacks. Given that this is the develop branch, I went with a
configuration that will use the latest release build for all ZenPacks
except for CatalogService which will use the latest pre-release build.
See the docstring for the zenpackDownload() method in
artifact_download.py for a full description of the "zenpack" download
type's capabilities.

Add "zenpack" downloader type

---

Jenkins-image.groovy
versions.mk

Intended for use with changes in https://github.com/zenoss/zenoss-deploy/pull/114. 
The intention is NOT to run this job to release artifacts to the stable repo. The expectation is that the appliance-build job will be executed manually at release time to build a new appliance instance based on released artifacts.
The purpose of these changes is to:
1. Work with the changes in https://github.com/zenoss/zenoss-deploy/pull/114. 
2. Consolidate version information in versions.mk so that when we setup builds for a future support/5.x.y branch only have to modify versions.mk.

Parameterize the CC version identification into versions.mk

---

devimg/build-devbase.sh
devimg/build.sh
devimg/makefile
product-base/Dockerfile.in
product-base/install_scripts/create_devimg.sh
product-base/install_scripts/create_zenoss.sh
product-base/install_scripts/init_devimg_zenhome.sh
product-base/install_scripts/zenoss_component_install.sh
product-base/install_scripts/zenoss_init.sh
product-base/install_scripts/zp_install.py
product-base/makefile

See comments in [devimg/makefile](./devimg/makefile) for more details on how devimg is built.
A typical invocation by zendev would look something like:
```
cdz product-asembly
cd devimg
ZENDEV_ROOT=$HOME/src/metis SRCROOT=$HOME/src/metis/src TARGET_PRODUCT=core make clean build
```
The result will be two docker images:
```
zendev/devimg:metis
zendev/devimg-base:metis
```

Initial creation of devimg

---

devimg/build.sh
product-base/install_scripts/zp_install.py

1. Always remove the devimg build container
2. Fail the build if a requested zenpack can not be installed

More refinement found during devimg work

---

artifact_download.py
component_versions.json

The prodbin build hasn't been moved over yet, so I changed component_versions.json to explicitly use the old jenkins server

Default jenkins downloader to new platform-jenkins server

---

product-base/install_scripts/zp_install.py

Fixes a bug in RM pipeline builds which started recently when we started raising exceptions for missing ZPs.  The bug actually occurred when more than 1 zenpack matched the globbing check.
In the case of RM, that was ZenPacks.zenoss.ZenMail and ZenPacks.zenoss.ZenMailtx. Both are present and valid, but the `len(zpFileName) != 1` was failing when zpFileName was ZenPacks.zenoss.ZenMail.

Refine duplicate ZP check

---

artifact_download.py

Also makes it easier for developers how have SSH creds setup of jenkins.

Switch default repo URL to SSH format for easier interop with jig

---

product-base/install_scripts/install_lib.sh

The crashes have this message in the log:
```
"Failed to create cookie file '/var/lib/rabbitmq/.erlang.cookie': eacces"
```
For examples, see resmgr-pipeline build 82, core-pipeline builds 150 and 141.
Discussion of using `rabbitmqctl status` to resolve the race here - https://bugzilla.redhat.com/show_bug.cgi?id=1059913
PS. Have we had problems with Rabbit not starting in the field? Maybe something like this occassionally happens at runtime??

Implement workaround for occassional erlang crashes on rabbit startup

---

artifact_download.py

A recent pipeline job failed to download an artifact that should have been there.   There had been some recent networking problems so perhaps it was a temporary DNS or routing issue, but it was impossible to tell from the build log. This change reports the URL for a wider range of exceptions so if a similar problem occurs in the future, we will at least get the full URL for the jenkins download that failed.
Here is the error message from the build log that prompted this change:
```
[0m[91m+ artifactDownload zenoss.metric.consumer
+ local artifact=zenoss.metric.consumer
+ su - zenoss -c '/opt/zenoss/install_scripts/artifact_download.py --out_dir /tmp /opt/zenoss/install_scripts/component_versions.json zenoss.metric.consumer --reportFile /opt/zenoss/log/zenoss_component_artifact.log' …
```

Log URL of other types of download exceptions

---

versions.mk

After fixing ZEN-24517, bump the image version so that the build job uses the newer image.

Bump up HBase image version

---

versions.mk

versions.mk can't use makefile syntax, otherwise `zendev devimg` breaks

Restore java property-file syntax for HDFS_VERSION and OPENTSDB_VERSION

---

devimg/create_devimg.sh
devimg/makefile
devimg/zp_blacklist.json
product-base/install_scripts/zenoss_init.sh
product-base/install_scripts/zp_install.py

Adds the notion of a generic blacklist for zenpacks when building devimg.  The default list resides in `product-assembly/devimg/zp_blacklist.json` and currently is limited to just the CatalogService zenpack.
The makefile for devimg allows the caller to specify an override via the environment variable `ZENPACK_BLACKLIST` but I didn't extend that capability to zendev because it seems like a rare use case.   However, a zendev user can specify a custom list with a command like `ZENPACK_BLACKLIST=/path/to/my/custom/blacklist.json zendev devimg`
To test, I did the following:
```
zendev devimg --clean -p resmgr
zendev serviced -dx
<< start Zenoss.core services and verify all healthchecks >>
```

blacklist catalog service from devimg

---

product-base/install_scripts/zenoss_init.sh
product-base/install_scripts/zp_install.py

Without this change `make core` and `make resmgr` fail because they do not find `zp_blacklist.json` in the product-base image.

Make zp_blacklist.json optional for regular product builds

---

product-base/install_scripts/startZenossForTests.sh
product-base/install_scripts/starttests.sh

Split Zenoss startup into a separate script to facilitate interactive testing w/devimg. 
For example, as a developer I want to start RM from an interactive devimg shell once and run a series of tests.
Prereq for https://github.com/zenoss/zendev/pull/286

Refactor scripts for integration with zendev test

---

zenpack_versions.json

[Jira](https://jira.zenoss.com/browse/ZEN-25518)
The bug described in Jira is fixed in current development version of ZenPack.

ZEN-25518 Use develop version of DynamicServiceView ZenPack

---

zenpack_versions.json

https://jira.zenoss.com/browse/ZEN-25878
Per Glenn's recommendation, we can use develop for PredictiveThreshold.
It has commits with an important fix and a unit test fix.
Pending the next release of PredictiveThreshold, it might be a good idea to set it back to using latest release version.

Use pre for the PredictiveThreshold zenpack

---

zenpack_versions.json

ZEN-25880 - Upgrade to latest dev version of NetScreenMonitor to fix unit-test failure

Update NetScreenMonitor version to fix unit-tests

---

component_versions.json

This service-migration 1.1.3 is identical to 1.1.2; it was created in error.  However, we are using the latest in order to avoid future confusion.

Use service-migration 1.1.3

---

zenpack_versions.json

NetScreenMonitor was pointed to latest unstable build by 7593993 to pull
in a unit test fix for ZEN-25880. That fix has since been released in
2.2.2 via zenoss/ZenPacks.zenoss.NetScreenMonitor@1be8f20.

Update NetScreenMonitor: unstable to stable

---

zenpack_versions.json

vSphere was pointed to latest 3.5.* unstable build by d51720c and
00b569e to fix a unit test failure affecting the Metis build. The fix
for this unit test failure has now been released in vSphere 3.5.2 via
zenoss/ZenPacks.zenoss.vSphere@3f48715.

Update vSphere: 3.5.* to stable

---

devimg/docker_run_dumpzodb.sh
devimg/dump_zodb.sh
devimg/makefile

"make dumpdb" will start a new container based on devimg, start mariadb, redis, and rabbit, then wipe, reload, migrate, and dump the updated zodb XML and .gz files.

Add make target to dump clean, updated zodb

---

zenpack_versions.json

pin ZenPacks.zenoss.Microsoft.Windows version to hotfix 2.6.8

pin MSWin zenpack to hotfix 2.6.8 for ZEN-26086

---

zenpack_versions.json

All ZenPack versions are pinned except for CalculatedPerformance. It's
still pointing to the develop branch until testing is finished and an
appropriate stable version is released.
Refs ZEN-25991 and ZEN-26081.

Pin most ZenPack versions for 5.2.0 release

---

product-base/makefile

This change was made to support/5.2.x but not to develop.

ZEN-25998 Add check_for_old_servicedef to clean target

---

zenpack_versions.json

DigMonitor 1.1.1 hasn't been released. I pinned the wrong version in
4435c36 because a glitch in the Jenkins
develop-ZenPacks.zenoss.DigMonitor job built an egg with the stable
1.1.1 release version a while back so it became the newest stable build.
DigMonitor 1.1.0 is the latest stable release, and should be what goes
out with Zenoss 5.2.0.

Update DigMonitor ZenPack: 1.1.1 to 1.1.0

---

zenpack_versions.json

Changes from 3.5.2 to 3.5.3:
- Fix TypeError while adding vSphere hypervisor (ZEN-26197)
https://github.com/zenoss/ZenPacks.zenoss.vSphere/compare/3.5.2...3.5.3

Update vSphere ZenPack: 3.5.2 to 3.5.3

---

zenpack_versions.json

Changes from 2.5.0 to 2.5.2:
- Clarify and reduce chassis and server events (ZEN-25740)
- Fix zCredentialsZProperties override warning on Zenoss 5.2 (ZEN-26164)
https://github.com/zenoss/ZenPacks.zenoss.CiscoUCS/compare/2.5.0...2.5.2

Update CiscoUCS ZenPack: 2.5.0 to 2.5.2

---

Jenkins-image.groovy
Jenkins-promote.groovy
versions.mk

This allows a maintenance release of RM to be built with a GA release of CC.

Separate maturity levels for zenoss vs serviced

---

artifact_download.py
compare_builds.py

Downpayment for ZEN-25827 - does not currently include git changelog info
`compare_builds.py` compares the build logs from 2 different builds to identify which artifacts are different. By default, the comparison only reports differences. If you specify `-v`, it will report all artifacts, not just the different ones.
The following examples illustrate that the only difference between Core 5.2.0 RC2 and the Core 5.3.0 pipeline build 3 is zenoss-prodbin.   The ZenPacks output is particular reassuring because all of the zenpacks in Core 5.2.0 RC2 are pinned to a specific version, where as Core 5.3.0 on develop is pulling the most recently released ZPs - so that proves that pinned versions in 5.2.0 RC2 are really the latest ones.
**1. Compare 2 jenkins jobs**
```
$ ./compare_builds.py -b1 …
```

Add diff tooling

---

component_versions.json
versions.mk

This PR should NOT be merged until https://github.com/zenoss/zenoss-prodbin/pull/2010 has been merged and a new 5.2.1 prodbin artifact is available here - http://jenkins.zendev.org/job/zenoss-prodbin-merge-support-52x/

Bump version to 5.2.1

---

zenpack_versions.json

This is for getting this fix https://github.com/zenoss/ZenPacks.zenoss.Dashboard/pull/69 in 5.2.x
[JIRA](https://jira.zenoss.com/browse/ZEN-26254)

ZEN-26254: get develop of Dashboard into support/5.2.x

---

zenpack_versions.json

Changes from 2.5.2 to 2.5.4:
- Fix collection stall caused by interrupted connectivity. (ZPS-503)
https://github.com/zenoss/ZenPacks.zenoss.CiscoUCS/compare/2.5.2...2.5.4

Update CiscoUCS ZenPack: 2.5.2 to 2.5.4

---

zenpack_versions.json

Changes from 2.6.8 to 2.6.11:
- Fix Monitoring of SQL Instances results in a UUID error. (ZPS-453)
- Added additional event classes and handlers for Kerberos failures. (ZEN-25700)
- Added Auth event clears, getPingStatus includes /Status/Ping event class. (ZEN-25700)
- Fix Windows Shell Datasources are sending datamaps and bogging down ZenHub. (ZEN-26226)
https://github.com/zenoss/ZenPacks.zenoss.Microsoft.Windows/compare/2.6.8...2.6.11

Update Microsoft.Windows ZenPack: 2.6.8 to 2.6.11

---

core/zenpacks.json
core/zphistory.json
resmgr/zenpacks.json
resmgr/zphistory.json
ucspm/zenpacks.json
ucspm/zphistory.json
zenpack_versions.json

ZenPacks are going to start requiring this in the near future. Getting
this into all distributions (core, resmgr, ucspm) now will make
consuming other ZenPack updates easier for users.
Resolves ZPS-586.

Add ZenPackLib ZenPack: 2.0.0

---

core/zenpacks.json
core/zphistory.json
resmgr/zenpacks.json
resmgr/zphistory.json
ucspm/zenpacks.json
ucspm/zphistory.json
zenpack_versions.json

ZenPacks are going to start requiring this in the near future. Getting
this into all distributions (core, resmgr, ucspm) now will make
consuming other ZenPack updates easier for users.
Resolves ZPS-586.

(5.2.x) Add ZenPackLib ZenPack: 2.0.0

---

artifact_download.py

All of the following conditions must be met for a ZenPack artifact to be
considered pinned to a specific version.
The "pre" field is not true.
The "requirement" field is set.
The "requirement" field contains "===" (not just "==")
The "requirement" field does not contain a comma.

Fix ZenPack artifact pinning detection (5.2.x)

---

artifact_download.py

All of the following conditions must be met for a ZenPack artifact to be
considered pinned to a specific version.
- The "pre" field is not true.
- The "requirement" field is set.
- The "requirement" field contains "===" (not just "==")
- The "requirement" field does not contain a comma.

Fix ZenPack artifact pinning detection

---

zenpack_versions.json

Changes from 2.0.0 to 2.0.1:
- Ensure all datapoint attributes export to YAML (ZEN-26593)
- Ensure subsquent installations complete if ZP install fails (ZPS-627)
- Fixes for unit test failures in platform integration tests.
https://github.com/zenoss/ZenPacks.zenoss.ZenPackLib/compare/2.0.0...2.0.1

Update ZenPackLib ZenPack: 2.0.0 to 2.0.1 (5.2.x)

---

zenpack_versions.json

Back to referencing the latest stable ZenPackLib release now that the
2.0.1 hotfix has been released.

Update ZenPackLib ZenPack: hotfix/2.0.1 to master

---

zenpack_versions.json

Changes from 2.5.4 to 2.5.5:
- Fix warnings in modeling results. (ZPS-645)
- Fix CIMC "Maximum sessions reached" error. (ZPS-227)
https://github.com/zenoss/ZenPacks.zenoss.CiscoUCS/compare/2.5.4...2.5.5

Update CiscoUCS ZenPack: 2.5.4 to 2.5.5

---

artifact_download.py

Helpful for expedited debugging of error messages like this from http://platform-jenkins.zenoss.eng/job/product-assembly/job/develop/job/resmgr-pipeline/65:
```
Traceback (most recent call last):
File "../artifact_download.py", line 577, in <module>
main(options)
File "../artifact_download.py", line 329, in main
downloadArtifacts(options.versions, artifacts, options.out_dir, downloadReport)
File "../artifact_download.py", line 274, in downloadArtifacts
downloaders[versionInfo['type']](versionInfo, downloadDir, downloadReport)
File "../artifact_download.py", line 90, in zenpackDownload
zenpack = json.loads(urllib2.urlopen(url).read())
File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib64/python2.7/urllib2.py", line 437, in open …
```

Add more info when queries to zenosslabs fail

---

component_versions.json

A unit test of zep was revised so as to pass when it's run on devimg. To refelect this change, get zep artifacts from jenkins instead of dowloading from zenpip.

Get zep artifacts from jenkins

---

Jenkins-image.groovy

Fixes BLD-58.
This primarily for record-keeping or software archaeology; has no direct impact on the contents of the build artifacts

Log the exact commit of svcdefs going into any particular build

---

zenpack_versions.json

Fixes the build problem:
```
Traceback (most recent call last):
File "../artifact_download.py", line 581, in <module>
main(options)
File "../artifact_download.py", line 333, in main
downloadArtifacts(options.versions, artifacts, options.out_dir, downloadReport)
File "../artifact_download.py", line 278, in downloadArtifacts
downloaders[versionInfo['type']](versionInfo, downloadDir, downloadReport)
File "../artifact_download.py", line 99, in zenpackDownload
raise Exception("Error querying for ZP info from %s: %s" % (url, e))
Exception: Error querying for ZP info from http://zenpacks.zenosslabs.com/requirement/ZenPacks.zenoss.ControlCenter%3D%3D%3D1.5.%2A?pre: HTTP Error 404: Not Found
make: *** [zenpack_download] Error 1
```
from build …

Fix version info for CC ZenPack

---

core/upgrade-core.txt.in
resmgr/upgrade-resmgr.txt.in
ucspm/upgrade-ucspm.txt.in
versions.mk

fixes ZEN-26723: Upgrade scripts contain wrong image tag reference

---

common.mk
resmgr/upgrade-impact.txt.in

This is port from: https://github.com/zenoss/product-assembly/pull/235
[JIRA](https://jira.zenoss.com/browse/ZEN-26723)

ZEN-26723: add VERSION_TAG to impact upgrade script and missing sed

---

README.versionInfo.md

The previous examples used `>=` and would end up getting the newest
version overall, even if it was outside of the specified series.

docs: fix for specifying newest in series

---

zenpack_versions.json

Restoring ZenPackLib to latest stable release. Testing of the 2.0.2
hotfix has been finished.

Update ZenPackLib ZenPack: hotfix/2.0.2 to latest

---

zenpack_versions.json

Changes from 2.0.1 to 2.0.2:
- Only create a monitoring template if it changes or does not exist (ZPS-570)
- Ensure display of ZPL classes such as OSProcess in GUI elements (ZPS-572, ZPS-651)
https://github.com/zenoss/ZenPacks.zenoss.ZenPackLib/compare/2.0.1...2.0.2

Update ZenPackLib ZenPack: hotfix/2.0.2 to 2.0.2

---

build_status.py

Fixes cases like the failure in build 116 which was caused by the fact that the list of stage nodes for 'Run all product pipelines' included a 'Shell Script' node representing the `finally` block in the `Jenkins-begin.groovy` script.
Here's the link to the description of the begin job itself http://platform-jenkins.zenoss.eng/job/product-assembly/job/develop/job/begin/116/wfapi/describe
If you look at the last entry for the `stages` property,  you will find this reference for details about the 'Run all product pipelines' stage - 
http://platform-jenkins.zenoss.eng/job/product-assembly/job/develop/job/begin/116/execution/node/15/wfapi/describe
If you look at the `stageFlowNodes` in that link, you will that the first 2 entries represent the `appliance-build` jobs, and the last entry named …

Ignore 'sh' nodes in the stage flow

---

build_status.py

Trying again to ignore unexpected stages that appear when a job is cancelled.
In this case, aborting a downstream job triggered the execution flow for `Jenkins-begin.groovy` to execute that `catch` block which included a print statement that resulted in a `Print message` node in the stage details.  See http://platform-jenkins.zenoss.eng/job/product-assembly/job/develop/job/begin/
So this time, I ignore all stages for child jobs unless they begin with "Building "

More fixup for build_status.py

---

Jenkins-begin.groovy

Trying to correct the ambiguity in situations like this where the build actually failed, but the summary status in the HTML report was "ABORTED":
http://platform-jenkins.zenoss.eng/job/product-assembly/job/develop/job/begin/119/Build_Summary_Report/
Contrary to what I first thought, `hudson.AbortException` is issued both in cases where the `begin` job is aborted by the user, AND in cases when the downstream jobs fail. So this change is an attempt to be more selective in parsing the results.

Identify different types of aborted-job messages

---

Jenkins-begin.groovy
build_status.py

There are 2 problems in http://platform-jenkins.zenoss.eng/job/product-assembly/job/develop/job/begin/121/Build_Summary_Report/
Both have to do with the fact that when Jenkins executes the report script in the `finally` block, the `begin` job is not done - it's still an active running job.
1. The summary status for the `begin` job is "null". This is because when `currentBuild.status` was not set in the case of a successful job completion
2. The stage "Run all product pipelines" has an `IN_PROGRESS` status. This is potentially confusing.  Without doing more analysis of all of the child jobs/stages, it's difficult to know if the final status is SUCCESS or FAILURE, therefore just don't set the status field for stages or jobs which report `IN_PROGRESS`.

Workarounds for reporting while job is not finished

---

zenpack_versions.json

Changes from 2.0.2 to 2.0.3:
- Preserve ordering when loading multiple YAML files (ZPS-921)
- Fix setting of zProperty values when loading multiple YAML files (ZPS-925)
https://github.com/zenoss/ZenPacks.zenoss.ZenPackLib/compare/2.0.2...2.0.3

Update ZenPackLib: 2.0.2 to 2.0.3

---

Jenkins-promote.groovy

For image promote, pass SERVICED_BUILD_NUMBER to appliance jobs, not SERVICED_BUILD_NBR.
Note after 5.2.2 GA is released, another PR will correct this naming discrepancy across all of the scripts in this repo, but for now we just need to fix the image-promote because the release candidate builds for 5.2.2/1.2.3 have already been completed

Fix integration issue btwn image promote and appliance-builds

---

Jenkins-image.groovy
Jenkins-promote.groovy
versions.mk

Fixes an integration problem btwn the code in product-assembly and the code in zenoss-deploy.
The Jenkins job and the groovy scripts in zenoss-deploy expect a parameter named `SERVICED_BUILD_NUMBER` but the scripts in product-asembly were passing a parameter named`SERVICED_BUILD_NBR`
The build number for serviced is only used when building appliances that should include a GA version of serviced. Since this happens only occasionally, that's why this problem was missed.
This discrepancy was introduced after 5.2.0 was released. We didn't see it for the 5.2.1 release because one-off procedures were used during that release process.

Replace SERVICED_BUILD_NBR with SERVICED_BUILD_NUMBER

---

component_versions.json

Central query was pinned to v1.16 for the Metis release. Reverting the assembly build manifest for the 5.2.x central-query build to pull from central-query develop branch until Thebe release when central-query will be reversioned.

ZEN-27044 manifest change for central-query

---

zenpack_versions.json

Adding DurationThreshold to help ensure that customers using it get the
latest version needed to be compatible with the contextMetric change
introduced by ZEN-27003.
Fixes ZEN-27018.

Add DurationThreshold ZenPack

---

product-base/install_scripts/zp_install.py

Better to say we're installing a ZenPack before installing it instead of
after. It actually used to be this way, but the code around here churned
a few times and the stdout.flush() ended up inappropriately rearranged
to before the write to stdout.

Fix order of zenpack installation output

---

resmgr/zenpacks.json

DurationThreshold must be packaged with resmgr as of 5.3.0 to ensure
customers already using it get the DurationThreshold 2.0.2 upgrade
required for compatibility with contextMetric (ZEN-27003) support going
into Zenoss 5.3.0.
Fixes ZEN-27018 for Zenoss 5.3.0.

Package DurationThreshold 2.0.2 (not installed)

---

zenpack_versions.json

Changes from 2.3.0 to 2.3.2:
- Clarify event when aggregation operation is blank or invalid. (ZPS-71)
- Change default aggregation operation from blank to "sum". (ZPS-71)
- Support new contextMetric capability in Zenoss 5.2.3. (ZEN-27010)
https://github.com/zenoss/ZenPacks.zenoss.CalculatedPerformance/compare/2.3.0...2.3.2

Update CalculatedPerformance ZenPack: 2.3.0 to 2.3.2

---

zenpack_versions.json

Changes from 1.2.0 to 1.2.1:
- Support new contextMetric capability in Zenoss 5.2.3. (ZEN-27011)
https://github.com/zenoss/ZenPacks.zenoss.PredictiveThreshold/compare/1.2.0...1.2.1

Update PredictiveThreshold ZenPack: 1.2.0 to 1.2.1

---

zenpack_versions.json

Changes from 2.4.0 to 2.4.1:
- Support new contextMetric capability in Zenoss 5.2.3. (ZEN-27009)
https://github.com/zenoss/ZenPacks.zenoss.EnterpriseReports/compare/2.4.0...2.4.1

Update EnterpriseReports ZenPack: 2.4.0 to 2.4.1

---

zenpack_versions.json

Changes from 3.5.3 to 3.6.1:
- Analytics: Count vSphere devices in overall device inventory (add to dim_device) (ZPS-398)
- Fix improperly rounded 'Total' value on 'Performance Data Collection Counters' graph (ZPS-392)
- Fix calculation of missedRuns in zenvsphere by not counting event and modeler tasks (they are run constantly, and can never be 'late') (ZPS-399)
- Fix error while displaying VMs report (ZPS-337)
- Remove broken 'folder' links from component details (ZPS-396)
- Clarify resource pool counts on Datacenter components (ZPS-389)
- Suppress events when vSphere host is in maintenance mode (by setting Host and VM productionState accordingly) (ZPS-332)
- Fix modeling errors with VMs that are inside nested resource pools within vApps (ZPS-387)
- Updated to zenpacklib 1.1.2.
- Added …

Update vSphere ZenPack: 3.5.3 to 3.6.1

---

zenpack_versions.json

Changes from 3.6.1 to 3.6.2:
- Fix zVSphereLUNContextMetric NameError in zenhub.log. (ZPS-1184)
https://github.com/zenoss/ZenPacks.zenoss.vSphere/compare/3.6.1...3.6.2

Update vSphere ZenPack: 3.6.1 to 3.6.2

---

component_versions.json

SVC-1051 made changes to the service-migration component to prevent installation/upgrade of the incident management ZP from accidentally erasing the `Version` property on `Zenoss.resmgr`.  This change uses that modified version of the service-migration component so we can regress SVC-1051 in a build of Thebe.

Use 1.1.6-dev of service-migration to verify ZEN-27124

---

jobTemplate.json

The build report for core appliances was not ignoring unused stages because the jobPrefix in the template didn't match the actual job name

Correct job name for core appliances

---

zenpack_versions.json

Changes from 2.1.2 to 2.1.3:
- Properly account for reserved space to match df output. (ZPS-26739)
https://github.com/zenoss/ZenPacks.zenoss.LinuxMonitor/compare/2.1.2...2.1.3

Update LinuxMonitor ZenPack: 2.1.2 to 2.1.3

---

zenpack_versions.json

Setting LinuxMonitor back to the default of pointing to the latest
stable release. As of right now this will be LinuxMonitor 2.2.0.

Update LinuxMonitor ZenPack: hf/2.1.3 to stable

---

component_versions.json

First commit to get modelindex into the image.  We need it in component_versions so the Jenkins job that builds it will work.  Then we will go back and add it to the image

Add modelindex to component_versions

---

devimg/create_devimg.sh
product-base/install_scripts/zenoss_component_install.sh

Installs latest modelindex develop build into $ZENHOME/modelindex in the zenoss base image.
Links in modelindex source in devimg build.

Add model index to image and devimg

---

devimg/create_devimg.sh
product-base/install_scripts/zenoss_component_install.sh

This has broken the build.  We will re-instate modelindex later as a wheel.

Temporarily back out modelindex

---

devimg/create_devimg.sh
product-base/install_scripts/zenoss_component_install.sh

The modelindex tarball now includes wheels for modelindex and all requirements.  The requirements for modelindex are already included in pydeps, so when building the image, we install only the modelindex wheel.
When building a devimg, we link in the mounted source code and install it in editable mode.

install model index from wheel

---

product-base/install_scripts/create_zenoss.sh
product-base/install_scripts/install_lib.sh
product-base/install_scripts/zenoss_init.sh

During zenoss initialization, we start solr.  If the code for initializing model catalog exists, we run it after zodb is initialized.

Initialize model catalog

---

zenpack_versions.json

Changes from 2.1.3 to 2.2.0:
- Add disk id modeling for correlation with underlying hardware. (ZPS-510)
- Add link to underlying hardware from disk details if possible. (ZPS-939)
- Handle root filesystem reservation more like "df" command. (ZPS-1266)
- Fix NFS filesystem monitoring not working as expected. (ZPS-1006)
https://github.com/zenoss/ZenPacks.zenoss.LinuxMonitor/compare/2.1.3...2.2.0

Update LinuxMonitor: 2.1.3 to 2.2.0

---

zenpack_versions.json

Required by ZenPacks.zenoss.Microsoft.Windows 2.7.0.
Changes from 2.0.4 to 2.0.5:
- Fix version reported by "zenpacklib --version". (ZPS-1145)
- Template backups use YYYYMMDDHHMM format instead of unix timestamp.
- Fix failure to back up customized templates during upgrade from pre-2.0 ZenPacks. (ZPS-1195)
- Fix failure to back up customized templates during upgrade. (ZPS-1176)
https://github.com/zenoss/ZenPacks.zenoss.ZenPackLib/compare/2.0.4...2.0.5

Update ZenPackLib: 2.0.4 to 2.0.5

---

zenpack_versions.json

Version 1.2.1 contains a unittest fix necessary for building appliances.

BLD-75 Bump DiscoveryMapping to 1.2.1

---

component_versions.json

Port of #351.
Fixes ZEN-27374.

Use 2.1.0 release of zenoss.toolbox

---

zenpack_versions.json

- CalculatedPerformance updated to 2.4.1
- CiscoUCSCentral updated to 1.3.0
- CiscoUCS updated to 2.6.0
- EMC.base updated to 1.2.0
- Microsoft.Windows updated to 2.7.0
- NetAppMonitor updated to 3.5.0
- PythonCollector updated to 1.9.0
- UCSCapacity updated to 1.3.0
- UCSXSkin updated to 2.1.8

BLD-111 Update several ZPs for UCS-PM

---

zenpack_versions.json

Changes from 1.2.0 to hotfix/1.2.1:
- Enable adding VNX File devices from multi-device add wizard (ZPS-1440)
- Fix "old_data_path" errors on Zenoss 5.2.3 and newer (ZPS-1392)
https://github.com/zenoss/ZenPacks.zenoss.EMC/compare/1.2.0...hotfix/1.2.1

Update EMC ZenPack: 1.2.0 to hotfix/1.2.1

---

component_versions.json

configure Thebe builds to use develop builds of zproxy toward features around special purpose dedicated Zope instances.

feature ZEN-27471: use develop version of zproxy in develop builds

---

zenpack_versions.json

The hotfix/1.2.2 branch was released as 1.2.2. So the develop branch of
product-assembly should be restored to including the latest release of
PredictiveThreshold. That would be 1.2.2 as of the time of this commit.

Update PredictiveThreshold: 1.2.2dev to latest

---

zenpack_versions.json

Changes from 1.2.1 to 1.2.2:
- Add unit of measure to graph export (ZEN-19837)
https://github.com/zenoss/ZenPacks.zenoss.PredictiveThreshold/compare/1.2.1...1.2.2

Update PredictiveThreshold ZenPack: 1.2.1 to 1.2.2

---

component_versions.json

This is required for zendev init, and zendev restore to work with
support/5.2.x. Without this change the following errors occur.
$ zendev restore support/5.2.x
ZENDEV: Checking out 'support/5.2.x' for product-assembly ...
ZENDEV: Generating list of github repos and versions ...
ZENDEV: Checking out github repos defined by /z/ucspm/.zendev/.repos.json
ERRO[0003] Problem running git command     cmd=git clone --progress git@github.com:zenoss/service-migration.git /z/ucspm/src/github.com/zenoss/service-migration path=. repo=github.com/zenoss/service-migration
ERRO[0003] Problem running git command     cmd=git fetch --progress --all path=/z/ucspm/src/github.com/zenoss/service-migration repo=github.com/zenoss/service-migration
ERRO[0003] Unable to checkout ref          err= ref=1.1.7 …

Specify git_owner for service-migration

---

zenpack_versions.json

Changes from 2.2.0 to 2.2.2:
- Improved OS Model parser for os_release modeler plugin. (ZPS-1177)
- Fix query service overloading during Analytics ETL of Linux devices. (ZPS-1312)
- Honor zFileSystemIgnoreTypes in zenoss.cmd.linux.df modeler plugin. (ZPS-1494)
https://github.com/zenoss/ZenPacks.zenoss.LinuxMonitor/compare/2.2.0...2.2.2

Update LinuxMonitor: 2.2.0 to 2.2.2

---

zenpack_versions.json

Temporarily build from CiscoUCS hotfix/2.6.1 branch instead of a tagged
release so QA can test incoming changes for UCS-PM "Juliet".
Current changes from 2.6.0 to hotfix/2.6.1:
- Add UCS device types to multi-device add wizard. (ZPS-1421)
- Fix CIMC severity comment graph points. (ZPS-1361)
- Set zCollectorClientTimeout to 600 (ZPS-1519)
More changes may occur before the UCS-PM "Juliet" release.
https://github.com/zenoss/ZenPacks.zenoss.CiscoUCS/compare/2.6.0...hotfix/2.6.1

Update CiscoUCS: 2.6.0 to hotfix/2.6.1

---

zenpack_versions.json

Temporarily build from CiscoUCSCentral hotfix/1.3.1 branch instead of a
tagged release so QA can test incoming changes for UCS-PM "Juliet".
Current changes from 1.3.0 to hotfix/1.3.1:
- Add Cisco UCS Central to multi-device add wizard (ZPS-1421)
- Fix templates showing in profiles list (ZPS-668)
More changes may occur before the UCS-PM "Juliet" release.
https://github.com/zenoss/ZenPacks.zenoss.CiscoUCSCentral/compare/1.3.0...hotfix/1.3.1

Update CiscoUCSCentral: 1.3.0 to hotfix/1.3.1

---

common.mk

Fix adds another line in common.mk to replace %UCSPM_VERSION% with the value for $UCSPM_VERSION
[Jira](https://jira.zenoss.com/browse/CC-3557)

CC-3557 UCSPM Version should be used for upgrade script

---

common.mk

port from https://github.com/zenoss/product-assembly/pull/388
[Jira](https://jira.zenoss.com/browse/CC-3552)

CC-3552 UCSPM Version should be used for upgrade script

---

Jenkins-begin.groovy
Jenkins-image.groovy
Jenkins-promote.groovy

Now that we've updated jenkins, we can correct the groovy syntax to prevent warnings like:
```
[Pipeline] stage (Build product-base)
Using the ‘stage’ step without a block argument is deprecated
Entering stage Build product-base
```

Fix Jenkins deprecated warnings

---

Jenkins-begin.groovy
Jenkins-image.groovy
Jenkins-promote.groovy

Apparently the upgrade to Jenkins combined with using proper `{...}` bracing for each `stage()` created a scoping problem such that variables defined in the first stage were not accessible to later stages.   This change defines those types of variables at the top of the `node()` method, and then populates them in the first stage.
In http://platform-jenkins.zenoss.eng/job/product-assembly/job/develop/job/core-pipeline/221/, see
```
[Pipeline] { (Compile service definitions and build RPM)
[Pipeline] sh
[core-pipeline] Running shell script
+ rm -rf svcdefs/build
+ mkdir -p svcdefs/build/zenoss-service
[Pipeline] dir
Running in /workspace/workspace/product-assembly/develop/core-pipeline/svcdefs/build/zenoss-service
[Pipeline] {
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage …
```

Fix problem with variable scoping

---

build_status.py

Fixes this failure:
```
[begin] Running shell script
+ ./build_status.py -b develop -p 244 --job-name begin --job-status FAILURE -html buildReport.html
INFO:root:begin:product build #244 @docker-centos-7-3 - FAILURE
INFO:root:found 3 stage(s) for 'Run all product pipelines'
INFO:root:core-pipeline:product build #244 (pipeline job #223 @docker-centos-7-12) - FAILED
Traceback (most recent call last):
File "./build_status.py", line 623, in <module>
main(options)
File "./build_status.py", line 589, in main
report = buildReport(templates, beginJobInfo, "begin")
File "./build_status.py", line 373, in buildReport
addChildJobs(stageTemplate, templates, stage, jobs)
File "./build_status.py", line 435, in addChildJobs
childJobReport = buildReport(templates, jobInfo, jobName)
File …
```

Remove incorrect argument

---

Jenkins-begin.groovy
Jenkins-image.groovy
Jenkins-promote.groovy
build_status.py
jobTemplate.html
jobTemplate.json

Updates to groovy scripting and reporting for a combination of Jenkins server upgrades and changes to the build process to build master and delegate appliances in parallel.
Includes changes from BLD-136 and BLD-149
Also see https://github.com/zenoss/zenoss-deploy/pull/563

Backport changes from BLD-149

---

zenpack_versions.json

The 1.3.1 hotfix was released so we can now released the tagged version.
Changes from 1.3.0 to 1.3.1:
- Add Cisco UCS Central to multi-device add wizard. (ZPS-1421)
- Fix templates showing in service profiles list and vice versa. (ZPS-668)
https://github.com/zenoss/ZenPacks.zenoss.CiscoUCSCentral/compare/1.3.0...1.3.1

Update CiscoUCSCentral: hotfix/1.3.1 to 1.3.1

---

zenpack_versions.json

The 2.6.1 hotfix was released so we can now release the tagged version.
Changes from 2.6.0 to 2.6.1:
- Add UCS device types to multi-device add wizard. (ZPS-1421)
- The severity comment graph points were properly aligned on the CIMC graphs. (ZPS-1361)
- Increase default modeling timeout from 3 to 10 minutes. (ZPS-1519)
- Fix "ssl handshake failure" error on adding a CIMC 3.0 device. Add zCiscoUCSCIMCSSLProtocol zProperty. (ZPS-1365)
- Add a "Cisco UCS Manager - Huge Spikes on Utilization Graphs" record to the Troubleshooting section. (ZPS-1190)
https://github.com/zenoss/ZenPacks.zenoss.CiscoUCS/compare/2.6.0...2.6.1

Update CiscoUCS: hotfix/2.6.1 to 2.6.1

---

zenpack_versions.json

The 1.2.1 hotfix was released so we can now release the tagged version.
Changes from 1.2.0 to 1.2.1:
- Enable adding VNX File devices from multi-device add wizard (ZPS-1440)
- Fix "old_data_path" errors on Zenoss 5.2.3 and newer (ZPS-1392)
https://github.com/zenoss/ZenPacks.zenoss.EMC.base/compare/1.2.0...1.2.1

Update EMC.base: hotfix/1.2.1 to 1.2.1

---

zenpack_versions.json

The develop branch was released as 1.4.0 so now we can release the
tagged version.
Changes from 1.3.0 to 1.4.0:
- Fix event links from Integrated Infrastructure portlet. (ZEN-14934)
- Fix capacity legend on reports to work on Zenoss 5.2. (ZPS-1500)
https://github.com/zenoss/ZenPacks.zenoss.UCSCapacity/compare/1.3.0...1.4.0

Update UCSCapacity: develop to 1.4.0

---

component_versions.json

Update to use metricshipper 1.1.4 release.
Update to use metric.consumer 0.1.7 release.

Use released metricshipper and consumer.

---

zenpack_versions.json

A regression was introduced in 2.6.6 that prevents SQLTx datasources
from being monitored at all. ZenSQLTx 2.6.6 with this regression was
shipped with RM 5.2.3 and 5.2.4. This change will prevent it from being
shipped with 5.2.5.
Changes being reverted (2.6.6 to 2.6.5):
- Fix SQL datasource test to test from appropriate collector (ZEN-22199)
https://github.com/zenoss/ZenPacks.zenoss.ZenSQLTx/compare/2.6.6...2.6.5
Refs ZPS-1657.

Revert ZenSQLTx: 2.6.6 to 2.6.5

---

jobTemplate.json

Not building QCOWs will save 10-15 minutes from the total nightly build time

Remove QCOWs from the build

---

component_versions.json

This is in support of the 5.2.6 backport for debug-Zopes and API-Zopes

ZEN-27838: use develop version of zproxy until 1.0.3 is released

---

component_versions.json

https://jira.zenoss.com/browse/ZEN-27644
Bring in the latest query code for updated graphs.  The query repo will need to be released and this version updated when we release 5.2.6.

Use the latest query code until we're ready to release 5.2.6

---

jobTemplate.json

Reverts zenoss/product-assembly#451
Turns out somebody wants qcows

Revert "Remove QCOWs from the build to save time"

---

jobTemplate.json

Reverts zenoss/product-assembly#449
Turns out somebody wants them

Revert "Remove QCOWs from the build"

---

zenpack_versions.json

2.2.5 has been released so we can now pin the version instead of building the
hotfix branch. Noting changes from 2.2.2 to 2.2.5 because prior to switching
to building the hotfix/2.2.5 branch, we were including LinuxMonitor 2.2.2 with
Zenoss 5.2.x releases.
Changes from 2.2.2 to 2.2.5:
- Use FileSystem_NFS_Client template for all NFS mounts (including nfs4). (ZPS-1495)
- Prevent the creation of orphaned processes when an NFS mount becomes unavailable. (ZPS-1499)
- Fix "IndexError" when modeling tun interfaces. (ZPS-971)
- Add percentUsed datapoint for filesystems. Use for UI and events. (ZPS-1545)
- Escape the commandTemplate expression for disk and idisk datasources to avoid TALES errors. (ZPS-1616)
- Fix RPN errors in aliases for memory, swap, and LVM (ZPS-757)
- Fix modeler …

Update LinuxMonitor: hotfix/2.2.5 to 2.2.5

---

versions.mk

This version of the opentsdb image includes a script
that collects metrics from Infrastructure opentsdb and
sends it to CC's opentsdb for self-monitoring purposes.

ZEN-27335 Use opentsdb image tag 24.0.6

---

Jenkins-begin.groovy
Jenkins-image.groovy
Jenkins-promote.groovy
versions.mk

1. Use the updated service-definitions to get the right version (depends on https://github.com/zenoss/zenoss-service/pull/418 being merged first)
2. Take the value of the `BRANCH` parameter from the begin job and pass it down the `appliance-build` job so that zenoss-deploy builds appliances from the same branch named used to launch the build. 
PS. To get the later to work, I changed the Jenkins job definitions for support-5.2.x `core-pipeline`, `resmgr-pipeline` and `ucspm-pipeline` to add a new parameter named `BRANCH`

Change for hotfix build

---

core/upgrade-core.txt.in
resmgr/upgrade-impact.txt.in
resmgr/upgrade-resmgr.txt.in

https://jira.zenoss.com/browse/ZEN-27524
Needs https://github.com/zenoss/zenoss-prodbin/pull/2517 for dont-bump option.

ZEN-27524: Update/delete migrate scripts that use deleted catalogs

---

zenpack_versions.json

Changes from 2.2.2 to 2.2.3:
- Fix aliases for standard reports (ZPS-1390)
https://github.com/zenoss/ZenPacks.zenoss.AixMonitor/compare/2.2.2...2.2.3

Update AixMonitor: 2.2.2 to 2.2.3

---

zenpack_versions.json

Changes from 2.0.2 to 2.0.4:
- Restore event.current field to be current value of datapoint. (ZPS-1223)
- Clear misconfiguration events when configuration is fixed. (ZPS-675)
- Encode self.TimePeriod in checkRaw() into an ascii string. (ZPS-1420)
https://github.com/zenoss/ZenPacks.zenoss.DurationThreshold/compare/2.0.2...2.0.4

Update DurationThreshold: 2.0.2 to 2.0.4

---

zenpack_versions.json

Changes from 2.0.1 to 2.0.2:
- Fix process monitoring for newer Zenoss versions. (ZPS-711)
https://github.com/zenoss/ZenPacks.zenoss.HpuxMonitor/compare/2.0.1...2.0.2

Update HpuxMonitor: 2.0.1 to 2.0.2

---

zenpack_versions.json

Changes from 2.2.5 to 2.2.6:
- Fix issue with links between Linux and NetApp FileSystem components. (ZPS-1736)
- Prevent the creation of orphaned processes when an NFS mount becomes unavailable. (ZPS-1499)
- Document support for RHEL 7, Ubuntu 16.04 LTS, and Debian 8. (ZPS-1820)
- Fix spurious warnings in zencommand log when monitoring NFS mounted filesystems. (ZPS-1823)
- Calculate memory utilization using "MemAvailable" when possible. (ZPS-1144)
- Fix 0.0% utilization in Windows filesystem threshold event summaries. (ZPS-1844)
https://github.com/zenoss/ZenPacks.zenoss.LinuxMonitor/compare/2.2.5...2.2.6

Update LinuxMonitor: 2.2.5 to 2.2.6

---

zenpack_versions.json

Changes from 1.3.2 to 1.3.3:
- Fix erroneous Hyper-V VM creation events. (ZPS-841)
https://github.com/zenoss/ZenPacks.zenoss.HyperV/compare/1.3.2...1.3.3

Update HyperV: 1.3.2 to 1.3.3

---

zenpack_versions.json

Changes from 2.7.4 to 2.7.8:
- Fix Windows ZP uses a lot of RAM when it contains hundreds of components due to checking for IIS (ZPS-1576)
- Fix Microsoft Windows: zenpython memory usage increases until restart required (ZPS-1584)
- Fix traceback during modeling (ZPS-1599)
- Fix redundant publishing of service state datapoints (ZPS-1604)
- Fix HardDisks with a size of 'None' cause unhandled exceptions in modeling (ZPS-1424)
- Fix Log line for "periodic maintenance" shows in incorrect logs (ZPS-1600)
- Fix Failed model job does not result in event (ZPS-1608)
- Fix Performance tables are not created even though performance batch is successful (ZPS-1605)
- Fix Traceback modelling with WinMSSQL plugin (ZPS-1676)
- Fix Custom command needs to allow datapoints with non-zero exit codes …

Update Windows: 2.7.4 to 2.7.8

---

zenpack_versions.json

Changes from 3.0.7 to 3.0.9:
-   Give datasource events unique eventKeys to avoid false-clearing (ZPS-500)
-   Set default timeouts for data collection DB connection (ZPS-313)
-   Update events and event class mappings to facilitate transforms (ZPS-500)
https://github.com/zenoss/ZenPacks.zenoss.MySqlMonitor/compare/3.0.7...3.0.9

Update MySqlMonitor: 3.0.7 to 3.0.9

---

zenpack_versions.json

Changes from 2.2.2 to 2.2.3:
- Add monitoring and locking to VPN tunnels. (ZPS-603)
https://github.com/zenoss/ZenPacks.zenoss.NetScreenMonitor/compare/2.2.2...2.2.3

Update NetScreenMonitor: 2.2.2 to 2.2.3

---

zenpack_versions.json

Changes from 1.1.0 to 1.1.1:
- Fix errors that can occur with components with certain characters in their IDs (ZPS-293)
https://github.com/zenoss/ZenPacks.zenoss.PropertyMonitor/compare/1.1.0...1.1.1

Update PropertyMonitor: 1.1.0 to 1.1.1

---

zenpack_versions.json

Changes from 1.9.0 to 1.10.1:
- Add "runningtimeout" option to zenpython. (ZPS-1675)
- Timeout datasources that stay running for triple their cycletime. (ZPS-1675)
- Add "timedOutTasks" metric to zenpython. (ZPS-1675)
- Fix RunningTimeoutError occurring instead of proper error. (ZPS-1755)
https://github.com/zenoss/ZenPacks.zenoss.PythonCollector/compare/1.9.0...1.10.1

Update PythonCollector: 1.9.0 to 1.10.1

---

zenpack_versions.json

Changes from 3.6.2 to 3.6.3:
- Fix issue that can cause duplicated components (ZPS-1614)
- Include vSphere devices in standard device tables in analytics (ZPS-1501)
https://github.com/zenoss/ZenPacks.zenoss.vSphere/compare/3.6.2...3.6.3

Update vSphere: 3.6.2 to 3.6.3

---

zenpack_versions.json

Changes from 3.0.0 to 3.0.1:
- Initial password is not displayed in ZenWebTx datasource. (ZPS-1289)
https://github.com/zenoss/ZenPacks.zenoss.ZenWebTx/compare/3.0.0...3.0.1

Update ZenWebTx: 3.0.0 to 3.0.1

---

zenpack_versions.json

Refs ZEN-28131.
---
**Version Changes**
- AixMonitor 2.2.3 (was 2.2.2)
- DurationThreshold 2.0.4 (was 2.0.4)
- HpuxMonitor 2.0.2 (was 2.0.1)
- LinuxMonitor 2.2.6 (was 2.2.5)
- Microsoft.HyperV 1.3.3 (was 1.3.2)
- Microsoft.Windows 2.7.8 (was 2.7.4)
- MySqlMonitor 3.0.9 (was 3.0.7)
- NetScreenMonitor 2.2.3 (was 2.2.2)
- PropertyMonitor 1.1.1 (was 1.1.0)
- PythonCollector 1.10.1 (was 1.9.0)
- StorageBase 1.4.3 (was 1.4.1)
- vSphere 3.6.3 (was 3.6.2)
- ZenWebTx 3.0.1 (was 3.0.0)
---
AixMonitor 2.2.2 -> 2.2.3
- Fix aliases for standard reports (ZPS-1390)
https://github.com/zenoss/ZenPacks.zenoss.AixMonitor/compare/2.2.2...2.2.3
---
DurationThreshold 2.0.2 -> 2.0.4
- Restore event.current field to be current value of datapoint. (ZPS-1223)
- Clear misconfiguration events when configuration is …

Update all Solutions ZenPacks for Amalthea

---

zenpack_versions.json

Changes from 2.2.3 to 2.3.0:
- Added JDBC monitoring template
- Updated documentation for newer versions of WebLogic Server
https://github.com/zenoss/ZenPacks.zenoss.WebLogicMonitor/compare/2.2.3...2.3.0

Update WebLogicMonitor: 2.2.3 to 2.3.0

---

component_versions.json

I moved all service-migration builds from `jenkins.zenoss.eng` to `platform-jenkins.zenoss.eng`.
The new develop build is here - http://platform-jenkins.zenoss.eng/job/ControlCenter/job/service-migration/job/develop/
Note that Thebe will use 1.1.10-dev of service-migration, while Amalthea is using the released version of 1.1.9

Pull dev build of service-migration from platform-jenkins

---

component_versions.json

Fixes problems with zendev like:
```
$ zendev restore develop
ZENDEV: Checking out 'develop' for product-assembly ...
ZENDEV: Generating list of github repos and versions ...
ZENDEV: Checking out github repos defined by /Users/glennjones/src/metis/.zendev/.repos.json
0 / ? [------------------------------------------------------------------------------------------------------------------=]ERRO[0000] Problem running git command                   cmd=git clone --progress git@github.com:zenoss/service-migration.git /Users/glennjones/src/metis/src/github.com/zenoss/service-migration path=. repo=github.com/zenoss/service-migration
ERRO[0000] Problem running git command                   cmd=git fetch --progress --all path=/Users/glennjones/src/metis/src/github.com/zenoss/service-migration …
```

Specify git info for service-migration

---

component_versions.json

In order to back out a fix for Thebe which is not ready for Amalthea.

Bump zproxy to 1.0.4

---

zenpack_versions.json

This ZP is not shipped with ZSD, but needs to be pinned to execute the standard 5.3.0 release process

Use most recent release of CiscoUCSCentral

---

component_versions.json

Change central query to develop to pick up changes from ZEN-28163 for ZEN-28183 for 5.3.1.

ZEN-28183: use develop for query service

---

core/upgrade-core.txt.in
resmgr/upgrade-impact.txt.in
resmgr/upgrade-resmgr.txt.in
ucspm/upgrade-ucspm.txt.in

Run reindex at end of upgrade, then re-run migrations that require model catalog

---

versions.mk

Update hbase-image (and opentsdb, etc.) to 24.0.8 for ZEN-28346

Use hbase-image 24.0.8

---

zenpack_versions.json

https://jira.zenoss.com/browse/ZEN-28739
I added new zenpacks to the manifest, but failed to add them to zenpack_version.  This adds them as develop versions, to be pinned on release.

Add missing zenpack versions

---

resmgr/zenpacks.json

Remove AWS zenpack to get a QA artifact built

Remove AWS zenpack to get artifact built

---

resmgr/zenpacks.json

The BigIpMonitor zenpack is in both installed and packaged zenpacks.  According to the planning list, this should not be installed by default - so removing that entry.

Remove duplicate BigIpMonitor entry

---

resmgr/zenpacks.json

https://jira.zenoss.com/browse/ZEN-28777
Now that the unit tests are passing, we need to add the AWS zenpack back into the manifest.

Add the AWS zenpack back into the manifest

---

resmgr/zenpacks.json

Reverts zenoss/product-assembly#545
Test-modules with import problems:
ZenPacks.zenoss.AWS.tests.test_dsplugins

Revert "Add the AWS zenpack back into the manifest"

---

resmgr/zphistory.json

https://jira.zenoss.com/browse/ZEN-28816
The AWS zenpack is failing unit tests, so was removed from the manifest to prevent build failures.  We didn't remove it from the zphistory.json file, however, causing upgrades to behave as if this zenpack had been intentionally removed from the manifest.
The zenpack will be added again once unit tests are sorted out.

AWS zenpack is failing unit tests; will be added back once fixed

---

product-base/install_scripts/create_zenoss.sh
product-base/install_scripts/install_lib.sh

https://jira.zenoss.com/browse/ZEN-28791
The mysqld_safe wrapper previously chowned /var/log/mysqld.log, but that was removed to prevent a possible security flaw (https://mariadb.com/kb/en/mariadb-10029-release-notes/).  The file must now needs to be created and chown'd to mysql manually.  See https://jira.mariadb.org/browse/MDEV-11841 for more information.

Initialize mysqld log file in the image

---

resmgr/zenpacks.json
resmgr/zphistory.json
zenpack_versions.json

https://jira.zenoss.com/browse/ZEN-28777
AWS 3.0.3 will be included in the Thebe manifest.
Passing test run at: http://platform-jenkins.zenoss.eng/job/TestBuilds/job/rp-develop-begin-pipeline/9/console

Add the updated AWS zenpack back into the manifest

---

zenpack_versions.json

Include ZenPacks.zenoss.CiscoUCS v2.6.2 and ZenPacks.zenoss.Microsoft.Windows v2.8.1 in the build.
Fixes ZEN-28888.

Update CiscoUCS and Windows ZenPack versions.

---

component_versions.json

https://jira.zenoss.com/browse/ZEN-28918
Fix problem with rabbit queues being previously defined with different create arguments.

Use 2.1.6 zenoss-protocols

---

component_versions.json

https://jira.zenoss.com/browse/ZEN-28918
Pull the support/6.0.x version of prodbin

Pull the support/6.0.x branch of prodbin

---

resmgr/upgrade-impact.txt.in

https://jira.zenoss.com/browse/ZEN-29087
Cherry-picked from https://github.com/zenoss/product-assembly/pull/583
Fixes the last commit that mistakenly removed the wait for Impact while adding a wait for memcached

Fixed earlier commit. Wait for Impact also

---

component_versions.json

https://jira.zenoss.com/browse/ZEN-29074
Use new protocols version to fix the eventlet queue creation path.

Use new zenoss-protocols

---

component_versions.json

Reverts zenoss/product-assembly#585
revert as it should go simultaneously with another fix https://github.com/zenoss/zenoss-prodbin/pull/2827 to prodbin, however  tests for it are failing and I can't commit. Revert until I have fixed unittests for zenoss-prodbin/pull/2827

Revert "ZEN-28754 Add new Router to the API to query model catalog bypassing …"

---

zenpack_versions.json

Temporarily using the unreleased hotfix/3.3.1 branch for HP Proliant to
fix a unit test that was broken by the fix for ZEN-28507.
https://github.com/zenoss/ZenPacks.zenoss.HP.Proliant/compare/3.3.0...hotfix/3.3.1

Update HP.Proliant: 3.3.0 to hotfix/3.3.1

---

zenpack_versions.json

HP.Proliant 3.3.1 has been released. Pinning it for develop.
Changes from 3.3.0 to 3.3.1:
- Updated unit tests for build platform compatability (ZPS-29150, ZEN-28507)
https://github.com/zenoss/ZenPacks.zenoss.HP.Proliant/compare/3.3.0...3.3.1

Update HP.Proliant: 3.3.1dev to 3.3.1

---

zenpack_versions.json

LinuxMonitor 2.2.7 has been released. Pinning it for develop.
Changes from 2.2.6 to 2.2.7:
- Allow for restricted dmesg access in Debian 9 and SUSE 12. (ZPS-1933, ZPS-550)
https://github.com/zenoss/ZenPacks.zenoss.LinuxMonitor/compare/2.2.6...2.2.7

Update LinuxMonitor: 2.2.7dev to 2.2.7

---

resmgr/zenpacks.json

Fixes https://jira.zenoss.com/browse/ZPS-2709
Predictive Threshold zenpack should be installed before EMC.base

ZPS-2709: Change zenpacks installation order

---

resmgr/zenpacks.json

Fixes https://jira.zenoss.com/browse/ZEN-29292
Predictive Threshold zenpack should be installed before EMC.base

ZEN-29292: Change zenpacks installation order

---

devimg/docker_run_dumpzodb.sh
product-base/makefile

* Use most recent version of zenoss-centos-base
* Properly mount source when performing a "dumpdb"

Use zenoss-centos-base 1.2.13

---

zenpack_versions.json

Changes from 2.0.8 to 2.0.9:
- Fix incorrect removal of organizers such as /Status event class (ZPS-2660)
https://github.com/zenoss/ZenPacks.zenoss.ZenPackLib/compare/2.0.8...2.0.9

Update ZenPackLib: 2.0.8 to 2.0.9

---

product-base/makefile

This version of zenoss-centos-base uses the latest version of zenoss-pydeps, which updates the python cryptography package to version 1.9.

Use zenoss-centos-base 1.2.14

---

zenpack_versions.json

AWS 4.0.1 is new version.
Dashboard and DynamicView are being pinned back to their previous releases.

Pin AWS, Dashboard, and DynamicView for 6.1.1

---

artifact_download.py

IT is deprecating the zenosslabs.com domain. Both will be in place for
some time, but we need to start using the zenoss.eng equivalents ASAP.

Replace zenosslabs.com domain with zenoss.eng

---

product-base/makefile

Pin Dione to zenoss-centos-base 1.2.16

---

product-base/makefile

Pin Zenoss 6.1.2 to zenoss-centos-base 1.2.16

---

zenpack_versions.json

This mismatch was preventing `zendev restore` and `zendev devimg --clean --product cse` from working properly.

fix mismatch between json file and branch name in repo

---

component_versions.json

This build contains the fix for leaked file descriptors when SNMP v3 authentication fails (ZEN-29805).

Use pynetsnmp develop branch build.

---

zenpack_versions.json

https://jira.zenoss.com/browse/ZEN-30081
Bring in the develop version of the AdvancedSearch zenpack so the virtualRoot prefix is prepended to search results.

Use the develop version of AdvancedSearch ZP

---

zenpack_versions.json

Pin vSphere zenpack to 3.6.3 for Dione.

---

component_versions.json

This version will not leak open socket descriptors when there's an SNMP v3 authentication error.
Fixes ZEN-30372.

Use 0.41.0 release of pynetsnmp.

---

zenpack_versions.json

The only update in 2.0.4 is a fix for a unit test failure on Zenoss 7.

Pin Docker to 2.0.4

---

zenpack_versions.json

Previous PR missed an extra `=` in the pinning statement

Tweak pinning syntax for a couple of ZenPacks

---

zenpack_versions.json

Use latest GA releases for various ZPs based on review with Rajan and Chris
Go back to use HP.Proliant hotfix/3.3.2 because we need the newer version to pass RM unit-tests

Adjust various ZP versions after further review

---

component_versions.json

metric consumer 0.1.9 has changes for https://jira.zenoss.com/browse/ZEN-3016, which are also required for https://jira.zenoss.com/browse/ZING-627

bump metric consumer to 0.1.9

---

zenpack_versions.json

Fixes ZEN-30730.
LinuxMonitor 2.3.1 has issues that won't be resolved in time for the 6.2.1 release.

Pin LinuxMonitor 2.2.7 to RM 6.2.1 release.

---

component_versions.json

https://jira.zenoss.com/browse/CC-3559
CC-3559 requires an updated service migration release in order to add additional properties to the health checks.

Package newest migration for HC changes

---

component_versions.json

https://jira.zenoss.com/browse/ZEN-30731
Add the new zproxy to support auth0 access tokens in the zapp lua file.

Bump zproxy to version 1.0.6

---

Jenkins-begin.groovy
artifact_download.py

ZING-1224
Adds option to check for latest zenpack versions and fails build if manifest doesn't match latest versions
Example failure http://platform-jenkins.zenoss.eng/job/product-assembly/job/develop/job/begin/381/console

Check latest

---

component_versions.json

pin develop the version to get changes from 
https://github.com/zenoss/query/pull/341

ZEN-29982: reportmail does not work for graph reports

---

component_versions.json

Components pinned:
- query 0.1.33
- zenoss.toolbox 2.3.0
- pynetsnmp 0.41.1
- modelindex 1.0.4
Fixes BLD-212.

More 6.3 component pinnings.

---

component_versions.json
zenpack_versions.json

- Pin prodbin component to 7.0.8
- Pin ZenPacks.zenoss.RMMonitor back to 1.1.1
Fixes ZING-2046.

Pin prodbin and RMMonitor for 7.0.8

---

Jenkins-begin.groovy

This is the first part of fixes for this ticket.
Added step which generates Python's packages list and archive it as build job artifacts.

ZEN-31234 Add automated check of 3rd-party Python packages

---

cse/zenpacks.json
cse/zphistory.json

The UCSCapacity ZP is merged into CiscoUCS ZP and is no longer required. This change updates the order of install of these two ZP's where we upgrade UCSCapacity first, if it's installed, and then upgrade CiscoUCS.

Update install order for CiscoUCS release

---

zenpack_versions.json

The changes related to ZEN-31678 resulted in most ZenPacks with
DynamicView or Impact unit tests now having failing unit tests. To this
end, they have all received updates in a hotfix branch to make their
unit tests be actually correct, and work with DynamicView 1.7.0 and
Impact 5.4.9.
Once DynamicView 1.7.0 and Impact 5.4.9 are released, these ZenPack
hotfixes can be released. Then we can pin them all back to tagged
releases.
Refs ZEN-31678.

pin ZenPacks with Impact unit tests to hotfix

---

zenpack_versions.json

Layer2's impact relationships adapter was found to be a significant
contributor to the time spent building impact relationships in some
environments. A change to optimize this has been added to Layer2's
hotfix/1.4.3 branch.
We're pulling this in prior to releasing and pinning Layer2 1.4.3
because further changes may be desired before the next CZ release.
Refs ZPS-5712.

use Layer2 hotfix/1.4.3 branch

---

zenpack_versions.json

A defect (ZPS-5713) existed in HP Proliant impact relationship providers
that could result in an exception. Any relationship provider that
results in an exception could be responsible for leaving the other side
of the relationship in an uncorroborated state.
Refs ZPS-5713.

use HP.Proliant hotfix/3.3.3 branch

---

zenpack_versions.json

A change in ApplyDataMap going into Zenoss 7.0.12? has resulted in
problem when the same datamaps are reused to model different devices.
This change fixes the one affected unit test in ZenPackLib by having it
regenerate the datamaps for each device.
Refs ZPS-5741.

use ZenPackLib hotfix/2.1.2 branch

---

zenpack_versions.json

A change in ApplyDataMap going into Zenoss 7.0.12? has resulted in a
problem when the same datamap is reused. This change fixes the one
affected unit test in PythonCollector by having it regenerate datamaps
for each use.
Refs ZPS-5763.

use PythonCollector hotfix/1.10.2 branch

---

zenpack_versions.json

SolarisMonitor was found to have impact relationship providers that
provided uncorroborated and otherwise inconsistent impact relationships.
These problem have been corrected in the hotfix/2.5.3 branch.
Refs ZPS-5769.

use SolarisMonitor hotfix/2.5.3 branch

---

zenpack_versions.json

MySqlMonitor was found to have uncorroborated impact relationship
providers. This has been fixed on the hotfix/1.1.3 branch.
Refs ZPS-5772.

use IBM.Power hotfix/1.1.3 branch

---

zenpack_versions.json

MySqlMonitor was found to be providing uncorroborated impact
relationships. Its hotfix/3.1.1 branch has a fix for this.
Refs ZPS-5774.

use MySqlMonitor hotfix/3.1.1 branch

---

zenpack_versions.json

The NetAppMonitor ZenPack was found to be providing duplicate and
uncorroborated impact relationships. These have been corrected in the
hotfix/4.0.1 branch.
Refs ZPS-5779.

use NetAppMonitor hotfix/4.0.1 branch

---

zenpack_versions.json

The ApplyDataMap changes introduced under ZEN-31166 caused some ZenPack
unit tests to break. These ZenPack unit tests have been fixed in hotfix
branches, and are pending release. We need to include them in the build
to ensure that the fixes were successful.
Refs ZEN-31166.

update ZenPacks to fix ADM unit test failures

---

Jenkins-begin.groovy

I've already added the RUN_TESTS parameter to http://platform-jenkins.zenoss.eng/job/product-assembly/job/develop/job/begin/build.

BLD-226: parameterize product-assembly begin to allow skipping of tests

---

zenpack_versions.json

Pin ZenPacks.zenoss.Dashboard to 1.3.7 release.

---

zenpack_versions.json

Pin DistributedCollector to 3.1.8 release.

---

zenpack_versions.json

Switching from hotfix/1.10.2 to develop (1.11.0) because QA is going to
focus on testing and releasing 1.11.0 instead of 1.10.2.
Refs ZPS-5763.

use PythonCollector develop (1.11.0) branch

---

zenpack_versions.json

Pin EnterpriseCollector to its 1.9.0 release.

---

versions.mk

Pin zenoss-services to 7.0.12 release.

---

component_versions.json

Pin zenoss-prodbin to its 7.0.12 release.

---

zenpack_versions.json

- CalculatedPerformance 2.5.2
- Ceph 2.1.0
- CiscoUCS 2.8.1
- ComponentGroups 1.8.0
- DynamicView 1.7.0
- IBM.Power 1.1.3
- Layer2 1.4.2
- LinuxMonitor 2.3.3
- PythonCollector 1.11.0.dev
- vSphere 4.0.2

ZEN-31756: update ZenPacks for Impact 5.5

---

core/zenpacks.json
cse/zenpacks.json
cse/zphistory.json
resmgr/zenpacks.json
zenpack_versions.json

backport https://github.com/zenoss/product-assembly/pull/903

ZEN-31557: Add FTPMonitor to the  Zenpack manifest

---

zenpack_versions.json

Reverting pins for
ZenPacks.zenoss.DynamicView
ZenPacks.zenoss.PythonCollector
to get a build.
Working on failing tests

ZEN-31909: 6.x product-assembly begin failed with unit test failures

---

zenpack_versions.json

Upgrading to DynamicView 1.7.0 in 77c6fc7 resulted in the following
ZenPack unit test errors and failures.
Tests with errors:
test_DynamicView (ZenPacks.zenoss.CiscoMonitor.tests.test_dvi.TestCiscoMonitor_DVI)
test_DynamicView (ZenPacks.zenoss.Docker.tests.test_dvi.DVITests)
Tests with failures:
test_dv_consistent (ZenPacks.zenoss.EMC.base.tests.test_dynamicview.TestDynamicView)
test_onSuccess (ZenPacks.zenoss.NetAppMonitor.tests.testMonitoring.Test7ModeMonitoring)
test_onSuccess (ZenPacks.zenoss.NetAppMonitor.tests.testMonitoring.TestCModeMonitoring)
These test problems should be corrected in the latest hotfix branches of
the associated ZenPacks. So I'm pulling in those hotfix builds. These
hotfixes will need to be released and pinned here later.
Fixes ZEN-31909.

ZEN-31909: fix ZenPack unit test problems

---

Jenkins-begin.groovy
Jenkins-image.groovy

Adds support for an IGNORE_TEST_IMAGE_FAILURE flag that, when set, will allow the pipeline to continue executing rather than failing.
Fixes ZEN-31916.

Add optional flag to ignore Test-Image failures.

---

zenpack_versions.json

Some of these pinned versions are known to have unit test errors and/or
failures with DynamicView 1.7.x and Impact 5.5.x. We're OK with those
specific unit test problems for now.

ZEN-31756: pin all ZenPack versions for 6.4

---

zenpack_versions.json

Since RMMonitor 1.2.0 is scheduled for inclusion in RM 6.4.0, use the RMMonitor 1.2.0 unstable builds for the Zenoss 6.4 unstable builds.
ZEN-31782

Use RMMonitor 1.2.0 unstable builds.

---

component_versions.json

Use 0.1.12 release of metric-consumer.

---

product-base/makefile

ZEN-32335: bump centos-base version to 1.2.23

---

component_versions.json

Unpin zenoss-zep to use develop build.

---

component_versions.json

Pin zenoss-zep to the 2.7.3 release.

---

cse/upgrade-cse.sh.in

Use the name of the image ID used in the mariadb-model service's definition to determine whether it needs to be replaced with the name of the mariadb image.
Fixes ZEN-32454.

Use image ID to determine mariadb migration.

---

product-base/makefile

Use zenoss-centos-base 1.2.24 image for CZ builds.

---

zenpack_versions.json

Roll back EnterpriseSecurity to the 1.2.0 release.

---

devimg/create_devimg.sh
devimg/devtestshell.sh
product-base/install_scripts/install_lib.sh
product-base/install_scripts/rabbitmq_lib.sh
test_image.sh

This also requires a zendev update so that it calls the test_image.sh script.
Fixes ZEN-32746.

The 'zendev test' command works again.

---

build_images.sh
resmgr/makefile

The --no-quickstart option tells the build process is to disable the installation wizard.
Fixes ZEN-32779.

Enable the installation wizard.

---

mariadb-base/upgrade_database.sh

* mysqladmin shutdown also requires credentials when password is set
* no space between -p and password

fix upgrade when custom passwords in use

---

product-base/install_scripts/create_zenoss.sh
product-base/install_scripts/databases_lib.sh

Applies ZODB migrations without having to update the zodb.sql.gz data dump.  The dump will happen when prodbin is released.
Fixes ZEN-33055.

Run zenmigrate as part of build.

---

product-base/install_scripts/zenoss_component_install.sh

The zenoss-prodbin artifact already provides it.
Fixes ZEN-33350.

No longer need to generate a ZVersion.py file.

---

Jenkins-begin.groovy
Jenkins-promote.groovy

The Jenkins-begin.groovy and Jenkins-promote.groovy scripts now build the service template package the same way.
Fixes ZEN-33302.

Make service template builds consistent.

---

mariadb-base/fix_permissions.sql.in
mariadb-base/makefile
mariadb-base/upgrade_database.sh

The permissions of an upgraded database should match an initial database.
Fixes ZEN-33446.
(cherry picked from commit 718b15ffa5765c2dd05ac39b5b57aa132095c6e0)

Clean up mariadb permissions during upgrade.
