zenoss/product-assembly

product-base/Dockerfile, product-base/install_scripts/install_lib.sh, product-base/install_scripts/zenoss_component_install.sh
=> add icmpecho

Jenkins-image.groovy
Starts the new jenkins job http://test-jenkins.zenoss.eng/job/product-assembly-develop/job/appliance-build, which primarily executes the new script https://github.com/zenoss/zenoss-deploy/blob/develop/jenkins/build-appliances.sh
=> Enable appliance builds

zenpack_versions.json
read the commit title and meditate upon it.
=> point Dashboard zp at develop

Jenkins-begin.groovy, Jenkins-image.groovy
DOH! - job parameters are set as Groovy variables on entry to the script
=> Use groovy vars for job parameters for effectively

supplementary.json
Add serviced-resource-agents and QuickVis to the list of supplementary repos
=> update supplementary repos

zenpack_versions.json
https://jira.zenoss.com/browse/ZEN-26080
=> Pin PredictiveThreshold ZP to 1.2.0

zenpack_versions.json
https://jira.zenoss.com/browse/ZEN-26080
=> Use latest release version for PredictiveThreshold ZP

zenpack_versions.json
Fixes [ZEN-26075](https://jira.zenoss.com/browse/ZEN-26075)
=> CatalogService uses latest release version

zenpack_versions.json
Fixes [ZEN-26075](https://jira.zenoss.com/browse/ZEN-26075)
=> CatalogService uses 3.1.1

zenpack_versions.json
https://jira.zenoss.com/browse/ZEN-26077
=> Use latest released version of ControlCenter ZP

zenpack_versions.json
https://jira.zenoss.com/browse/ZEN-26077
=> Pin version 1.3.0 for ControlCenter ZP

component_versions.json
http://platform-jenkins.zenoss.eng/job/Components/job/zenoss.metric.consumer/job/master/3/
=> zenoss.metric.consumer 0.1.6

versions.mk
toward ZEN-26067: Create 5.2.x branches for zenoss service
=> feature/ZEN-26067: use support/5.2.x service defs

devimg/docker_run_dumpzodb.sh, devimg/dump_zodb.sh, devimg/makefile
=> Add make target to dump clean, updated zodb

product-base/makefile
Adds check_for_old_serviced.py to build-deps.
=> ZEN-25998 Add old servicedef check script to build-deps

Jenkins-promote.groovy, core/upgrade-core.txt.in, resmgr/upgrade-impact.txt.in, resmgr/upgrade-resmgr.txt.in, svcdefs/image_promote.sh, svcdefs/makefile, ucspm/upgrade-ucspm.txt.in
Still needs some critical lines uncommented when we're ready to really use it
=> Initial version of image promotion logic

Jenkins-promote.groovy, core/upgrade-core.txt.in, resmgr/upgrade-impact.txt.in, resmgr/upgrade-resmgr.txt.in, svcdefs/image_promote.sh, svcdefs/makefile, ucspm/upgrade-ucspm.txt.in
=> Cherry-pick ZEN-26087 fixes

product-base/makefile
=> ZEN-25998 Added old servicedef check to build-deps and clean targets

zenpack_versions.json
Changes from 1.3.0 to 1.4.1:
- Improved modeling performance for large Control Center instances. (ZEN-26191)
- Modeled templates are now local to the device instead of component. (ZEN-26191)
https://github.com/zenoss/ZenPacks.zenoss.ControlCenter/compare/1.3.0...1.4.1
=> Update ControlCenter ZenPack: 1.3.0 to 1.4.1

supplementary.json
=> Add the serviced-iso directory used for building appliances

core/upgrade-core.sh.in, resmgr/upgrade-resmgr.sh.in
This code was added for UCS-PM for ZEN-24124, but not for
resmgr or core targets.
=> ZEN-26569 Untag old preupgrade snapshots before upgrade

component_versions.json
For ZEN-26258, ZEN-26260, and ZEN-26321.
=> Use nightly to verify for maintenance release.

Jenkins-image.groovy
The code for this PR might be a little redundant.  But IMO this allows us to change values easily on the 5.2/1.3 build section as well as easily pull it out when the time comes.
=> adding zsd_alderaan build support

zenpack_versions.json
[Jira](https://jira.zenoss.com/browse/ZEN-26615)
Needed to verify zenoss/ZenPacks.zenoss.AdvancedSearch#14
=> Use develop of AdvancedSearch zenpack

Jenkins-promote.groovy
Fixes BLD-39
Update promotion to logic to promote multiple appliances for TARGET_PRODUCT=resmgr
In other words, this change mirrors changes to `Jenkins-image.groovy` which trigger multiple appliance builds for the `resmgr` RPM/docker-image build.
=> Update appliance promotion to include poc

zenpack_versions.json
- Facilitate testing prior to hotfix release
=> Point build to ZenPackLib 2.0.2 Prerelease hotfix build

common.mk, resmgr/upgrade-impact.txt.in
Additional changes according to comment in related [JIRA](https://jira.zenoss.com/browse/ZEN-22726)
=> ZEN-22726: add VERSION_TAG to impact upgrade script and missing sed

zenpack_versions.json
=> Update AdvancedSearch zenpack to fixed version

component_versions.json
Fixes ZEN-26859, ZEN-26779, ZEN-26646, ZEN-26258.
=> Use latest development Central Query.

Jenkins-image.groovy
ZSD_ALDERAAN - with RM 5.2.2GA
=> BLD-46 - Modifying build info

Jenkins-begin.groovy, Jenkins-image.groovy, build_status.py, jobTemplate.html, jobTemplate.json
These are changes to generate an HTML report for the entire build pipeline
=> Backport changes for DEVOPS-244

Jenkins-image.groovy, Jenkins-promote.groovy, artifact_download.py, versions.mk
Use "SERVICED_BUILD_NUMBER" everywhere for consistency with the appliance-build job and the scripts therein
=> Backport changes for BLD-76

Jenkins-image.groovy, jobTemplate.json
zsd_alderaan will be built by a new Jenkins job, independent of the 5.2.x build pipeline
=> Remove zsd_alderaan from 5.2.x pipeline

jobTemplate.json
companion to https://github.com/zenoss/zenoss-deploy/pull/466 - add content to appliance build summary report and exclude reporting for certain form factors
=> BLD-83: define build stage for QA automation

zenpack_versions.json
[Jira](https://jira.zenoss.com/browse/ZEN-26963)
=> ZEN-26963 use develop for ComponentGroups

zenpack_versions.json
[Jira](https://jira.zenoss.com/browse/ZEN-26674)
=> ZEN-26674 use develop for ComponentGroups

component_versions.json
https://jira.zenoss.com/browse/ZEN-26394
ref to https://github.com/zenoss/pynetsnmp/pull/23
=>  ZEN-26394 SNMPv3 INFORMS are not supported with our current code

zenpack_versions.json
Changes from 2.0.3 to 2.0.4:
- Fix for missing Dynamic View on some components (ZPS-703)
- Fix for failure to create device classes in uncommon case (ZPS-1012)
- Fix event class mappings with mismatched id and eventClassKey (ZPS-1016)
https://github.com/zenoss/ZenPacks.zenoss.ZenPackLib/compare/2.0.3...2.0.4
=> Update ZenPackLib: 2.0.3 to 2.0.4

component_versions.json
For [ZEN-27008](https://jira.zenoss.com/browse/ZEN-27008)
=> Use latest development Central Query

component_versions.json
https://jira.zenoss.com/browse/ZEN-26795
ref to https://github.com/zenoss/product-assembly/pull/273
=> ZEN-26795 SNMPv3 INFORMS are not supported with our current code 

Jenkins-begin.groovy, jobTemplate.json
=> BLD-75 add UCS-PM appliance pipeline

Jenkins-begin.groovy
=> BLD-75 fix: disable ucspm pipeline downstream

jobTemplate.json
=> Correct job name for core appliances

component_versions.json, product-base/install_scripts/zenoss_component_install.sh
=> Add solr to zenoss image

component_versions.json
[Jira](https://jira.zenoss.com/browse/ZEN-27057)
=> ZEN-27057 Use latest development Central Query

component_versions.json
Use latest development Central Query to receive fix in Thebe.
[Jira](https://jira.zenoss.com/browse/ZEN-27108)
=> ZEN-27108 Use latest development Central Query

component_versions.json, product-base/install_scripts/zenoss_component_install.sh
=> Add zenoss.toolbox to product base build

zenpack_versions.json
[Jira & Demo](https://jira.zenoss.com/browse/ZEN-23079)
=> ZEN-23079 Bump NetAppMonitor to 3.5.0

core/zenpacks.json
removing ntp monitor zp from core
Missed this the first time around
=> ZEN-25558 minor correction

Jenkins-image.groovy
=> unstable builds may optionally skip appliances.

Jenkins-begin.groovy
=> Forward build appliances flag to pipeline

Jenkins-begin.groovy, Jenkins-image.groovy
Fixes BLD-110 for support/5.2.x
=> Optionally build appliances

versions.mk
=> Upgrade hbase image version

zenpack_versions.json
=> Use v2.7.4 of Microsoft.Windows ZenPack

zenpack_versions.json
Use develop version of SupportBundle zenpack
[JIRA](https://jira.zenoss.com/browse/ZEN-27520)
=> ZEN-27520: changed api query to elstic

ucspm/zenpacks.json, ucspm/zphistory.json
[Jira](https://jira.zenoss.com/browse/BLD-143)
=> BLD-143 Discovery Mapping zp should be removed for UCS-PM

ucspm/zenpacks.json, ucspm/zphistory.json
port from https://github.com/zenoss/product-assembly/pull/383
[Jira](https://jira.zenoss.com/browse/BLD-119)
=> BLD-119 Discovery Mapping zp should be removed for UCS-PM

zenpack_versions.json
[JIRA](https://jira.zenoss.com/browse/ZEN-25267)
=> ZEN-25267: changed api query to elstic

product-base/install_scripts/install_lib.sh
Use the new reindex tool to initialize and index Solr.
Edit:
Merge simultaneously with https://github.com/zenoss/zenoss-prodbin/pull/2349
=> Use the new reindex tool

component_versions.json
ZEN-27696 - point manifest to develop versions of metricshipper and metricconsumer to pick up changes from ZEN-27694 (Metric "Tracer bullets")
=> Pick up Metric Tracer Bullet functionality

zenpack_versions.json
Reverts zenoss/product-assembly#415
=> Revert "ZEN-27702: Update Dashboard ZenPack: 1.2.5 to develop"

product-base/makefile
https://jira.zenoss.com/browse/ZEN-27755
Pull in updated zenoss-centos-base with os security patches and relstorage updates.
=> Bring in updated zenoss-centos-base

jobTemplate.json
Merge pull request #449 from zenoss/feature/BLD-156
=> Remove QCOWs from the build to save time

Jenkins-begin.groovy, Jenkins-image.groovy, Jenkins-promote.groovy
=> Pass BRANCH parameter to downstream jobs

zenpack_versions.json
https://jira.zenoss.com/browse/ZEN-27605
=> ZEN-27605 Loader for CiscoUCSCentral ZenPack

core/upgrade-core.txt.in, resmgr/upgrade-impact.txt.in, resmgr/upgrade-resmgr.txt.in
Part of https://jira.zenoss.com/browse/ZEN-27524
Related: https://github.com/zenoss/zenoss-prodbin/pull/2551
=> Run script to purge Catalog Service

core/licenses.core.html
Update the core license file.  Relates to https://jira.zenoss.com/browse/ZEN-28144
=> ZEN-28144 update core license file

resmgr/licenses.resmgr.html
Update RM license file.  Relates to https://jira.zenoss.com/browse/ZEN-28146
=> ZEN-28146 Update RM license file

zenpack_versions.json
https://jira.zenoss.com/browse/ZEN-28166
Fix the Move Device layout to show a scrollbar and properly position the collector list when the list scrolls off of the screen.
=> Use the latest DistributedCollector zenpack

zenpack_versions.json
Changes from 1.4.1 to 1.4.3:
- Fix incorrect DynamicView relations for ConvergedNetworkAdapter components. (ZPS-1162)
- Fix issue which caused to missing data on analytics server. (ZPS-1673)
https://github.com/zenoss/ZenPacks.zenoss.StorageBase/compare/1.4.1...1.4.3
=> Update StorageBase: 1.4.1 to 1.4.3

zenpack_versions.json
https://jira.zenoss.com/browse/ZEN-28003
Update to pull in the latest LDAPAuthenticator ZenPack code.
=> Use prerelease LDAPAuthenticator zenpack

component_versions.json
=> Specify git info for service-migration

zenpack_versions.json
[Jira](https://jira.zenoss.com/browse/ZEN-28286)
=> ZEN-28286 use develop for Dashboard

core/upgrade-core.txt.in, resmgr/upgrade-impact.txt.in, resmgr/upgrade-resmgr.txt.in
https://jira.zenoss.com/browse/ZEN-28340
=> Add rm/core 5.3

zenpack_versions.json
https://jira.zenoss.com/browse/ZEN-28455
=> ZEN-28455 Include instance identifier in zendiag's output filename

versions.mk
Fixes https://jira.zenoss.com/browse/ZEN-28498
=> Use hotfix/5.3.1 branch for service definitions

zenpack_versions.json
bump version for support because of PR https://github.com/zenoss/ZenPacks.zenoss.DistributedCollector/pull/63
=> ZEN-28357: new arguments to extend remodel API functionality

zenpack_versions.json
[Jira](https://jira.zenoss.com/browse/ZEN-28456)
=> ZEN-28456 use develop for LDAPAuthenticator zp

component_versions.json
[Jira](https://jira.zenoss.com/browse/ZEN-28243)
=> ZEN-28243 use zproxy develop builds

resmgr/zphistory.json
https://jira.zenoss.com/browse/ZEN-28647
=> ZEN-28647 Add RMMonitor ZenPack to zphistory

core/Dockerfile.in, core/current_version.txt, core/upgrade-core.sh.in, resmgr/Dockerfile.in, resmgr/current_version.txt, resmgr/upgrade-resmgr.sh.in, ucspm/Dockerfile.in, ucspm/current_version.txt, ucspm/upgrade-ucspm.sh.in
https://jira.zenoss.com/browse/ZEN-28647
=> ZEN-28647 Preserve current version number of RM/Core/UCSPM

zenpack_versions.json
except calculatedperformance, for now.
=> Pin ZenPack versions to the latest releases

core/upgrade-core.txt.in, resmgr/upgrade-resmgr.txt.in, ucspm/upgrade-ucspm.txt.in
https://jira.zenoss.com/browse/ZEN-29075
Call a script that conditionally forces the catalog reindex if we're adding Solr.
=> Call a script to conditionally force a catalog reindex

resmgr/upgrade-impact.txt.in
https://jira.zenoss.com/browse/ZEN-29075
Apply the conditional upgrade script to the impact upgrade script as well.
=> Do not force a catalog reindex in the impact script unless upgrading <6 to 6+

zenpack_versions.json
[JIRA](https://jira.zenoss.com/browse/ZEN-28116)
=> ZEN-28116: bump ComponentGroups zp to develop

zenpack_versions.json
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-28979)
=> ZEN-28979: bump Dashboard zp to develop

zenpack_versions.json
=> Use PowerEdge ZenPack v2.0.4

component_versions.json
Pin query and modelindex to the new release versions.
=> Pin query to 0.1.28 and modelindex to 1.0.1

zenpack_versions.json
licensing details with silent failure
=> ZEN-28615 Update Report button on Licensing tab does not update

zenpack_versions.json
=> Pin ZenPackLib 2.0.8

zenpack_versions.json
[JIRA](https://jira.zenoss.com/browse/ZEN-29152)
=> ZEN-29152: using dev version of CC zenpack

zenpack_versions.json
[JIRA](https://jira.zenoss.com/browse/ZEN-29113)
=> ZEN-29113: using dev version of RM zenpack

zenpack_versions.json
https://jira.zenoss.com/browse/ZEN-29539
=> ZEN-29539 Update Pinnings for ZenPacks Round 2

zenpack_versions.json
https://jira.zenoss.com/browse/ZEN-29540
=> ZEN-29540 Update Pinnings for ZenPacks Round 2

cse/upgrade-cse.sh.in, cse/upgrade-cse.txt.in
https://github.com/zenoss/product-assembly/pull/635
=> ZEN-29315: Update CSE

core/upgrade-core.txt.in, cse/upgrade-cse.txt.in, resmgr/upgrade-impact.txt.in, resmgr/upgrade-resmgr.txt.in, ucspm/upgrade-ucspm.txt.in
=> ZEN-29563: Cannot upgrade MultiRealmIP Zenpack from 2.2.2 to 2.2.3

cse/upgrade-cse.txt.in
port: https://github.com/zenoss/product-assembly/pull/669
=> ZEN-29548: Cannot upgrade MultiRealmIP Zenpack from 2.2.2 to 2.2.3

zenpack_versions.json
https://jira.zenoss.com/browse/ZEN-29735
=> ZEN-29735 Pin newly released ZPs

cse/licenses.cse.html
We have created a new license file as of April 2018.  Update the file in the rm.
=> ZEN-29870  Update license file

resmgr/licenses.resmgr.html
Created a new license file as of April 2018
=> ZEN-29871  update license file

core/licenses.core.html
We created new license files as of April 2018
=> ZEN-29871 update license file

zenpack_versions.json
[JIRA](https://jira.zenoss.com/browse/ZEN-29966)
=> ZEN-29966: tag develop version of RMMonitor zenpack

zenpack_versions.json
Fixes: BLD-207
* for bugfix ZEN-30039
=> BLD-207: Pin ZenPacks.zenoss.EnterpriseCollector 1.8.3

zenpack_versions.json
Fixes: BLD-208
* for bugfix ZEN-30039
=> BLD-208: Pin ZenPacks.zenoss.EnterpriseCollector 1.8.3

artifact_download.py, core/Dockerfile.in, doc_versions.json, product-base/install_scripts/zenoss_docs_install.sh, product-base/makefile, resmgr/Dockerfile.in
=> Install pdf docs in build rather than via prodbin.

product-base/install_scripts/zenoss_component_install.sh, product-base/makefile
=> Use zenoss-centos-base v1.2.17

product-base/install_scripts/zenoss_component_install.sh, product-base/makefile
=>  Use zenoss-centos-base v1.2.17

zenpack_versions.json
https://jira.zenoss.com/browse/IMP-488
Update to pull in build 8 of Impact.
=> Update Impact to build 9

zenpack_versions.json
https://jira.zenoss.com/browse/ZEN-30089
Use the latest ComponentGroup zenpack to update color scheme for ZEN-30089.
=> Use dev version of the ComponentGroup zenpack

zenpack_versions.json
https://jira.zenoss.com/browse/ZEN-30106
Update to use the latest hotfix branch
=> Update dynamic view to latest version

component_versions.json
=> Fix (near) infinite timeout in pynetsnmp.

Jenkins-promote.groovy
…images when coming from unstable maturity
=> Use BUILD_NUMBER instead of releasephase. Also, only look for pinned images when coming from unstable maturity

zenpack_versions.json
Remove extra comma that's breaking builds.
=> Fix zenpack versions file

component_versions.json, versions.mk
* bump the version from 7.0.0 to 7.0.1
* use `develop` for service definitions
* use latest prodbin build (7.0.3-dev) from the prodbin `develop` branch
=> Start 7.0.1 release

zenpack_versions.json
Tagging for https://github.com/zenoss/ZenPacks.zenoss.PredictiveThreshold/pull/26 changes
=> ZEN-30416: use dev version of predictive threshold zp

zenpack_versions.json
=> Pin LDAPAuthenticator to 3.3.1 for 6.2.1 release

zenpack_versions.json
update versions of
CiscoUCS: 2.8.0
OSI: 2.4.2
AWS: 4.0.2
HTTPMonitor: 3.0.4
=> ZEN-30661: pin Solutions ZPs

cse/zenpacks.json, zenpack_versions.json
Installing this ZP toward the end of the list makes the most sense to me, open to feedback...
=> ZEN-30723 - adding DiscoveryMapping 1.2.1 to the ZenPack manifest

component_versions.json
https://jira.zenoss.com/browse/ZEN-29802
=> ZEN-29802 Use pagination to run zencatalogscan

component_versions.json, zenpack_versions.json
pick up dev zenpacks with changes targeted at next cz
=> ZING-1121: release next CZ

zenpack_versions.json
pin develop version for getting changes from 
https://github.com/zenoss/ZenPacks.zenoss.Dashboard/pull/118
=> ZEN-30882: fix backward compatibility for older versions

zenpack_versions.json
=> Pin LinuxMonitor 2.3.2 for 6.3.0

component_versions.json
pining develop version of the query to get changes that were made in https://github.com/zenoss/query/pull/341
[JIRA](https://jira.zenoss.com/browse/ZEN-28763)
=> ZEN-28763: reportmail does not work for graph reports

component_versions.json
https://jira.zenoss.com/browse/ZING-1439
Update components to pin new query and prodbin
=> Pin prodbin and query to new versions

versions.mk
https://jira.zenoss.com/browse/ZING-1452
Pin service definitions.
=> Pin service definitions

zenpack_versions.json
=> Fix version pinning for Dashboard, LDAPAuth.

resmgr/zenpacks.json, zenpack_versions.json
Included but not installed.
Fixes BLD-212.
=> Include GoogleCloudPlatform ZP in resmgr.

resmgr/zenpacks.json, zenpack_versions.json
=> Add Kubernetes ZP to RM 6.3.0

component_versions.json
=> Pin ZEP 2.6.1 for RM 6.3.0

zenpack_versions.json
[Jira](https://jira.zenoss.com/browse/ZEN-30424)
=> ZEN-30424 use develop for ZenPacks.zenoss.InstalledTemplatesReport

zenpack_versions.json
=> Pin  v1.3.4 Dashboard ZP

zenpack_versions.json
=> Pin vSphere v4.0.1 dev build ZenPack.

component_versions.json
=> Pin zenoss-zep 2.7.1 release.

zenpack_versions.json
We are rolling back pinning on vSphere and Dell Poweredge to try and get the builds working.
=> ZING-1840 - Reverted vSphere ZP poweredge ZP pinning

zenpack_versions.json
=> Pin InstalledTemplatesReport 1.1.2 ZenPack

component_versions.json
=> Pin Query 0.1.33

zenpack_versions.json
=> Pin vSphere 4.0.1, PowerEdge 3.0.0 ZenPacks

component_versions.json, versions.mk
=> Pin prodbin 7.0.7 and service 7.0.7

README.md, compare_builds.py
ZING-1090
JSON output format added to `compare_builds.py` tool, which compatible with GitHub manifest for [changelog](https://github.com/zenoss/changelog) utility.
=> ZING-1090 Generate a changelog for product-assembly builds

zenpack_versions.json
This is to ensure the RMMon ZP updates in next release
=> Adding thresholds for ZEN-30231 and ZEN-30232

component_versions.json
This is a small change to point prodbin pinnings to develop branch.
=> ZEN-31232: moved prodbin pinning back to develop.

versions.mk
=> Update versions for 7.0.8 release.

Jenkins-begin.groovy, compare_pip.py
Added comparison utility, fixed Jenkins job.
=> ZEN-31234 Add automated check of 3rd-party Python packages

cse/zenpacks.json, zenpack_versions.json
Update ZenPack pinnings
Add Capacity ZP to package+install list
Remove Diagram ZP
=> ZEN-31312: update ZenPack pinnings

component_versions.json
=> Update prodbin to use 7.0.9 rc build.

component_versions.json
=> Update prodbin to 7.0.9 release build.

component_versions.json, versions.mk
=> Build with 7.0.10 development artifacts.

cse/upgrade-cse.txt.in
https://jira.zenoss.com/browse/ZEN-31430
Ops requested that all service starts/waits be together.
=> Batch all of the start/waits together

component_versions.json
=> Set prodbin to the 7.0.11 RC builds

zenpack_versions.json
=> Need 'git_ref' field for repos.sh script.

zenpack_versions.json
=> Pin AWS 4.1.1 and HttpMonitor 3.1.0 zenpacks.

versions.mk
=> Use zenoss-service release/7.0.11 branch for builds.

component_versions.json
=> Use prodbin 7.0.11 rc build

component_versions.json, versions.mk
=> pin release 7.0.11 prodbin and definitions

zenpack_versions.json
Set EnterpriseCollector to develop
=> Set EnterpriseCollector to develop

component_versions.json
Reverts zenoss/product-assembly#929
=> Revert "ZEN-31738: Bump zenoss-protocols version to dev"

zenpack_versions.json
=> Pin DiscoveryMapping to 1.2.3 release.

component_versions.json
This is required for the https://jira.zenoss.com/browse/CC-4209
=> Update service migration version

component_versions.json
https://jira.zenoss.com/browse/ZEN-31872
=> Update service-migration version

zenpack_versions.json
It's required for the ZEN-31253
=> Unpin Dashboard ZP

zenpack_versions.json
Reverts zenoss/product-assembly#978
=> Revert "ZEN-31909: fix ZenPack unit test problems"

zenpack_versions.json
=> Set Dashboard to develop

zenpack_versions.json
=> Unpin DistributedCollector ZP

Jenkins-promote.groovy, svcdefs/image_promote.sh
=> Add a promote mariadb image stage.

component_versions.json, product-base/install_scripts/install_lib.sh, product-base/install_scripts/zenoss_component_install.sh
=> Remove installation of icmpecho and pyraw.

cse/upgrade-cse.sh.in
=> Fix name of migrate step.

Jenkins-begin.groovy
Fixes BLD-230.
Test run with these changes (the actual push stages are skipped): http://platform-jenkins.zenoss.eng/job/TestBuilds/job/jpeacock/job/test_assembly/1/
=> Enable the Test Image stage

zenpack_versions.json
=> ZPS-6587: pin WSMAN v1.0.5

component_versions.json
Reverts zenoss/product-assembly#1054
=> Revert "Unpin zenoss-zep to use develop build."

cse/zenpacks.json, cse/zphistory.json, zenpack_versions.json
=> ZEN-32419 add ZenPacks.zenoss.CloudView to the CZ bundle

zenpack_versions.json
=> ZEN-32392: pin Dashboards to 1.3.10

cse/zenpacks.json, cse/zphistory.json, zenpack_versions.json
Also add the CloudView zenpack.
Fixes ZEN-32360.
=> Update ZenPacks for 7.0.14 release

versions.mk
=> Pin service defs to 7.0.14 release.

zenpack_versions.json
=> Pin StorageBase ZP to its 1.4.4 release.

component_versions.json
=> ZEN-32459: Pin zenoss-prodbin 7.0.15-master

cse/upgrade-cse.sh.in, versions.mk
merge git flow release changes
=> Feature/zen 32459.1

versions.mk
=> ZEN-32459: update service version

zenpack_versions.json
=> Use dev build of EnterpriseSecurity ZenPack.

mariadb/Dockerfile.in, mariadb/source_files_to_copy.txt
This commit includes "/opt/zenoss/Products/ZenUtils/ZenDB.py" and "/opt/zenoss/Products/ZenUtils/config.py", these scripts are needed for changes in https://github.com/zenoss/zenoss-prodbin/pull/3821
=> ZEN-32629 Update Dockerfile.in

product-base/makefile
Reverts zenoss/product-assembly#1118
=> Revert "ZEN-32720 Use zenoss-centos-base with updated phantomjs"

component_versions.json
=> Use 0.41.3 release of pynetsnmp.

mariadb-base/Dockerfile.in, mariadb-base/export_from_product_base.sh, mariadb-base/zencheckdbstats.py
For Ubuntu 20.04 environments, replace MySQLdb with pymysql.
Fixes ZEN-32648.
=> Update Python scripts to use pymysql.

mariadb-base/export_from_product_base.sh, mariadb-base/initialize_db.sh, mariadb-base/makefile, mariadb-base/source_files_to_copy.txt, mariadb-base/tools/Dockerfile.in, mariadb-base/tools/makefile, mariadb-base/tools/setup.py, mariadb-base/tools/src/zends/toolbox/config.py, mariadb-base/tools/src/zends/toolbox/sql/create_connection_info.sql, mariadb-base/tools/src/zends/toolbox/sql/create_killtx.sql, mariadb-base/tools/src/zends/toolbox/sql/has_connection_info.sql, mariadb-base/tools/src/zends/toolbox/sql/has_killtx.sql, mariadb-base/tools/src/zends/toolbox/zencheckdbstats.py, mariadb-base/tools/src/zends/toolbox/zencheckzends.py, product-base/Dockerfile.in
Collects the zencheckzends and zencheckdbstats tools into the zends.toolbox package.
The zends.toolbox package is installed into the base mariadb image.
Fixes ZEN-32843.
=> Install MariaDB tools as a package.

zenpack_versions.json
went ahead and pin unreleased version
=> ZEN-32898 Update Elm with recently GAed ZenPacks as of 6.5.0

product-base/makefile, svcdefs/makefile
=> Make zendev build work again

product-base/makefile, svcdefs/makefile
=> Make zendev build work again.

devimg/build.sh, devimg/install-activepython.sh, devimg/makefile
=> Install ActiveState Python into devimg builds too.

devimg/create_devimg.sh, devimg/fixup_path.sh, devimg/makefile
=> Ensure /opt/maven/bin is in PATH for devimg.

mariadb-base/Dockerfile.in
=> Retrieve Python 2 specific version of pip.

product-base/Dockerfile.in, product-base/sitecustomize.py
=> Suppress warnings about Python 2 obsolescence.

product-base/sitecustomize.py
=> Restore default/original warning filters.

install-activepython.sh
=> No need to make virtual env relocatable.

mariadb-base/upgrade_database.sh
=> Use syntax supported by Ubuntu's Dash shell.

resmgr/upgrade-impact.txt.in, resmgr/upgrade-resmgr.txt.in
=> Run the migration as the zenoss user.

common.mk, core/copy_upgrade_scripts.sh.in, core/current_version.txt, core/upgrade-core.sh.in, core/upgrade-core.txt.in, product-base/makefile, product-base/pull-docker-images.sh.in, resmgr/copy_upgrade_scripts.sh.in, resmgr/upgrade-impact.txt.in, resmgr/upgrade-resmgr.sh.in, resmgr/upgrade-resmgr.txt.in
=> Add mariadb image migration to core.

component_versions.json
=> ZEN-33601: Release 6.6.0

product-base/Dockerfile.in
=> Install Software Collections Python package.

zenpack_versions.json, zenpackadapter/install_scripts/zenoss_component_install.sh, zenpackadapter/zenpacks.json
updating zpa build to support LinuxMonitor and Windows ZenPacks
fixes (indirectly) zing-13517 and zing-14706
=> Adding LinuxMonitor and WIndows ZP

cse/copy_upgrade_scripts.sh.in
=> Create the /root/7.1.x directory before using it.
